//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePro.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPaymentDetail
    {
        public long PurchasePaymentID { get; set; }
        public long PurchaseID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentBy { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string PaymentStatus { get; set; }
    }
}
