//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePro.Repository.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PROTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PROTitle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparePro.Repository.Resource.PROTitle", typeof(PROTitle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Admin_Settings {
            get {
                return ResourceManager.GetString("Admin_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Brand.
        /// </summary>
        public static string Title_AddBrand {
            get {
                return ResourceManager.GetString("Title_AddBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Dashboard.
        /// </summary>
        public static string Title_BacktoDashboard {
            get {
                return ResourceManager.GetString("Title_BacktoDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Master - [Add/Edit].
        /// </summary>
        public static string Title_BrandMaster_AddEdit {
            get {
                return ResourceManager.GetString("Title_BrandMaster_AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Master.
        /// </summary>
        public static string Title_BrandMasterView {
            get {
                return ResourceManager.GetString("Title_BrandMasterView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Master - Search.
        /// </summary>
        public static string Title_ImageMaster_Setup_Search {
            get {
                return ResourceManager.GetString("Title_ImageMaster_Setup_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Master - View.
        /// </summary>
        public static string Title_ImageMaster_Setup_View {
            get {
                return ResourceManager.GetString("Title_ImageMaster_Setup_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Title_Logout {
            get {
                return ResourceManager.GetString("Title_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Setup - Search.
        /// </summary>
        public static string Title_Master_Setup_Search {
            get {
                return ResourceManager.GetString("Title_Master_Setup_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Setup - View.
        /// </summary>
        public static string Title_Master_Setup_View {
            get {
                return ResourceManager.GetString("Title_Master_Setup_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberShip Points Master - [Add/Edit].
        /// </summary>
        public static string Title_MemberShipPointsMaster {
            get {
                return ResourceManager.GetString("Title_MemberShipPointsMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Master Detail Add.
        /// </summary>
        public static string Title_MenuMaster_Detail_Add {
            get {
                return ResourceManager.GetString("Title_MenuMaster_Detail_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Master Detail Edit.
        /// </summary>
        public static string Title_MenuMaster_Detail_Edit {
            get {
                return ResourceManager.GetString("Title_MenuMaster_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Master Detail - Search.
        /// </summary>
        public static string Title_MenuMaster_Detail_Search {
            get {
                return ResourceManager.GetString("Title_MenuMaster_Detail_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Master Detail - View.
        /// </summary>
        public static string Title_MenuMaster_Detail_View {
            get {
                return ResourceManager.GetString("Title_MenuMaster_Detail_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Master Header Add.
        /// </summary>
        public static string Title_MenuMaster_Header_Add {
            get {
                return ResourceManager.GetString("Title_MenuMaster_Header_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Master Header Edit.
        /// </summary>
        public static string Title_MenuMaster_Header_Edit {
            get {
                return ResourceManager.GetString("Title_MenuMaster_Header_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Master Header - Search.
        /// </summary>
        public static string Title_MenuMaster_Header_Search {
            get {
                return ResourceManager.GetString("Title_MenuMaster_Header_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Master Header - View.
        /// </summary>
        public static string Title_MenuMaster_Header_View {
            get {
                return ResourceManager.GetString("Title_MenuMaster_Header_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Master.
        /// </summary>
        public static string Title_MenuMaster_View {
            get {
                return ResourceManager.GetString("Title_MenuMaster_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Project Setup.
        /// </summary>
        public static string Title_Project_Setup {
            get {
                return ResourceManager.GetString("Title_Project_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Master Detail.
        /// </summary>
        public static string Title_UserMasterDetail {
            get {
                return ResourceManager.GetString("Title_UserMasterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Admin.
        /// </summary>
        public static string Title_WelcomeAdmin {
            get {
                return ResourceManager.GetString("Title_WelcomeAdmin", resourceCulture);
            }
        }
    }
}
