//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePro.Repository.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SYSMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SYSMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparePro.Repository.Resource.SYSMessage", typeof(SYSMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Confirm Password.
        /// </summary>
        public static string ChangePassword_EnterConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePassword_EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        public static string ChangePassword_EnterNewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Old Password.
        /// </summary>
        public static string ChangePassword_EnterOldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_EnterOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Confirm Password Mismatch.
        /// </summary>
        public static string ChangePassword_NewAndConfirmPasswordMismatch {
            get {
                return ResourceManager.GetString("ChangePassword_NewAndConfirmPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is not correct.
        /// </summary>
        public static string ChangePassword_OldPasswordMismatch {
            get {
                return ResourceManager.GetString("ChangePassword_OldPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain one capital letter.
        /// </summary>
        public static string ChangePassword_PasswordCriteria_CapitalLetter {
            get {
                return ResourceManager.GetString("ChangePassword_PasswordCriteria_CapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length should be greater than 8.
        /// </summary>
        public static string ChangePassword_PasswordCriteria_Length {
            get {
                return ResourceManager.GetString("ChangePassword_PasswordCriteria_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain one letter.
        /// </summary>
        public static string ChangePassword_PasswordCriteria_OneLetter {
            get {
                return ResourceManager.GetString("ChangePassword_PasswordCriteria_OneLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain one number.
        /// </summary>
        public static string ChangePassword_PasswordCriteria_OneNumber {
            get {
                return ResourceManager.GetString("ChangePassword_PasswordCriteria_OneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Email Address.
        /// </summary>
        public static string Common_EnterValidEmailAddress {
            get {
                return ResourceManager.GetString("Common_EnterValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change..
        /// </summary>
        public static string Common_Unabletochange {
            get {
                return ResourceManager.GetString("Common_Unabletochange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove..
        /// </summary>
        public static string Common_UnableToRemove {
            get {
                return ResourceManager.GetString("Common_UnableToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Order by.
        /// </summary>
        public static string DefaultDetail_EnterDefaultOrder {
            get {
                return ResourceManager.GetString("DefaultDetail_EnterDefaultOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Default Text.
        /// </summary>
        public static string DefaultDetail_EnterDefaultText {
            get {
                return ResourceManager.GetString("DefaultDetail_EnterDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Default Type.
        /// </summary>
        public static string DefaultMaster_PleaseSelectDefaultHeader {
            get {
                return ResourceManager.GetString("DefaultMaster_PleaseSelectDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        public static string DropDownListSelect_Role {
            get {
                return ResourceManager.GetString("DropDownListSelect_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account is Locked. Please Contact Administrator.
        /// </summary>
        public static string Login_AccountLocked {
            get {
                return ResourceManager.GetString("Login_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string Login_EnterPassword {
            get {
                return ResourceManager.GetString("Login_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Name.
        /// </summary>
        public static string Login_EnterUsername {
            get {
                return ResourceManager.GetString("Login_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Password is incorrect.
        /// </summary>
        public static string Login_InvalidPassword {
            get {
                return ResourceManager.GetString("Login_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhar Number.
        /// </summary>
        public static string UserMaster_AadharNumber {
            get {
                return ResourceManager.GetString("UserMaster_AadharNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        public static string UserMaster_Address1 {
            get {
                return ResourceManager.GetString("UserMaster_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        public static string UserMaster_Address2 {
            get {
                return ResourceManager.GetString("UserMaster_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address3.
        /// </summary>
        public static string UserMaster_Address3 {
            get {
                return ResourceManager.GetString("UserMaster_Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salary.
        /// </summary>
        public static string UserMaster_BasicSalary {
            get {
                return ResourceManager.GetString("UserMaster_BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Joining.
        /// </summary>
        public static string UserMaster_DateOfJoining {
            get {
                return ResourceManager.GetString("UserMaster_DateOfJoining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Code.
        /// </summary>
        public static string UserMaster_EmployeeCode {
            get {
                return ResourceManager.GetString("UserMaster_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name.
        /// </summary>
        public static string UserMaster_EnterFirstName {
            get {
                return ResourceManager.GetString("UserMaster_EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name.
        /// </summary>
        public static string UserMaster_EnterLastName {
            get {
                return ResourceManager.GetString("UserMaster_EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Login Name.
        /// </summary>
        public static string UserMaster_EnterLoginName {
            get {
                return ResourceManager.GetString("UserMaster_EnterLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string UserMaster_EnterPassword {
            get {
                return ResourceManager.GetString("UserMaster_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Allowances.
        /// </summary>
        public static string UserMaster_FoodAllowances {
            get {
                return ResourceManager.GetString("UserMaster_FoodAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not allowed some Special Characters.
        /// </summary>
        public static string UserMaster_NotAllowedSpecialChar {
            get {
                return ResourceManager.GetString("UserMaster_NotAllowedSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Amount.
        /// </summary>
        public static string UserMaster_OTAmount {
            get {
                return ResourceManager.GetString("UserMaster_OTAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Number.
        /// </summary>
        public static string UserMaster_PanNumber {
            get {
                return ResourceManager.GetString("UserMaster_PanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select User.
        /// </summary>
        public static string UserMaster_PleaseSelectUser {
            get {
                return ResourceManager.GetString("UserMaster_PleaseSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User.
        /// </summary>
        public static string UserMaster_SelectUser {
            get {
                return ResourceManager.GetString("UserMaster_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Allowances.
        /// </summary>
        public static string UserMaster_TravelAllowances {
            get {
                return ResourceManager.GetString("UserMaster_TravelAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter  User Role Description.
        /// </summary>
        public static string UserRole_EnterRoleDescription {
            get {
                return ResourceManager.GetString("UserRole_EnterRoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Role Name.
        /// </summary>
        public static string UserRole_EnterRoleName {
            get {
                return ResourceManager.GetString("UserRole_EnterRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Home.
        /// </summary>
        public static string UserRole_SelectHome {
            get {
                return ResourceManager.GetString("UserRole_SelectHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Store.
        /// </summary>
        public static string UserRole_SelectStore {
            get {
                return ResourceManager.GetString("UserRole_SelectStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select User Role.
        /// </summary>
        public static string UserRole_SelectUserRole {
            get {
                return ResourceManager.GetString("UserRole_SelectUserRole", resourceCulture);
            }
        }
    }
}
