//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePro.Repository.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SYSPageModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SYSPageModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparePro.Repository.Resource.SYSPageModel", typeof(SYSPageModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ChangePassword_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangePassword_NewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string ChangePassword_OldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string Common_CreatedBy {
            get {
                return ResourceManager.GetString("Common_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string Common_CreatedDate {
            get {
                return ResourceManager.GetString("Common_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the information below. The field labels marked with * are required input fields..
        /// </summary>
        public static string Common_Hint {
            get {
                return ResourceManager.GetString("Common_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Common_Home {
            get {
                return ResourceManager.GetString("Common_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string Common_ModifiedBy {
            get {
                return ResourceManager.GetString("Common_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string Common_ModifiedDate {
            get {
                return ResourceManager.GetString("Common_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Common_Status {
            get {
                return ResourceManager.GetString("Common_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Text.
        /// </summary>
        public static string DefaultDetail_DefaultText {
            get {
                return ResourceManager.GetString("DefaultDetail_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string DefaultDetail_OrderBy {
            get {
                return ResourceManager.GetString("DefaultDetail_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DefaultMaster_DisplayOrder {
            get {
                return ResourceManager.GetString("DefaultMaster_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        public static string Index_CompanyDetails {
            get {
                return ResourceManager.GetString("Index_CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string Index_DashBoard {
            get {
                return ResourceManager.GetString("Index_DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        public static string Index_EmployeeDetails {
            get {
                return ResourceManager.GetString("Index_EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Count.
        /// </summary>
        public static string Index_ExpensesCount {
            get {
                return ResourceManager.GetString("Index_ExpensesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Index_Home {
            get {
                return ResourceManager.GetString("Index_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged Account Details.
        /// </summary>
        public static string Index_PasswordReset {
            get {
                return ResourceManager.GetString("Index_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Details.
        /// </summary>
        public static string Index_RoleDetails {
            get {
                return ResourceManager.GetString("Index_RoleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Count.
        /// </summary>
        public static string Index_SalesCount {
            get {
                return ResourceManager.GetString("Index_SalesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Return Count.
        /// </summary>
        public static string Index_SalesReturnCount {
            get {
                return ResourceManager.GetString("Index_SalesReturnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Void Count.
        /// </summary>
        public static string Index_SalesVoidCount {
            get {
                return ResourceManager.GetString("Index_SalesVoidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string Index_UserDetails {
            get {
                return ResourceManager.GetString("Index_UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Name.
        /// </summary>
        public static string ProjectSetupDetail_ConfigurationName {
            get {
                return ResourceManager.GetString("ProjectSetupDetail_ConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Value.
        /// </summary>
        public static string ProjectSetupDetail_Text {
            get {
                return ResourceManager.GetString("ProjectSetupDetail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Role_Description {
            get {
                return ResourceManager.GetString("Role_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is POS.
        /// </summary>
        public static string Role_IsPOS {
            get {
                return ResourceManager.GetString("Role_IsPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Description.
        /// </summary>
        public static string Role_RoleDescription {
            get {
                return ResourceManager.GetString("Role_RoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string Role_RoleName {
            get {
                return ResourceManager.GetString("Role_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Access.
        /// </summary>
        public static string RoleMatrix_AvailableAccess {
            get {
                return ResourceManager.GetString("RoleMatrix_AvailableAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled Access.
        /// </summary>
        public static string RoleMatrix_EnabledAccess {
            get {
                return ResourceManager.GetString("RoleMatrix_EnabledAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Access.
        /// </summary>
        public static string RoleMatrix_MenuAccess {
            get {
                return ResourceManager.GetString("RoleMatrix_MenuAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        public static string RoleMatrix_MenuName {
            get {
                return ResourceManager.GetString("RoleMatrix_MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Access.
        /// </summary>
        public static string RoleMatrix_PageAccess {
            get {
                return ResourceManager.GetString("RoleMatrix_PageAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Access View.
        /// </summary>
        public static string RoleMatrix_PageAccessView {
            get {
                return ResourceManager.GetString("RoleMatrix_PageAccessView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Role.
        /// </summary>
        public static string RoleMatrix_SelectRole {
            get {
                return ResourceManager.GetString("RoleMatrix_SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleSetUp_Role {
            get {
                return ResourceManager.GetString("RoleSetUp_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        public static string SalesPointsMaster_StoreName {
            get {
                return ResourceManager.GetString("SalesPointsMaster_StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string Tooltip_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Tooltip_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Default Text Field.
        /// </summary>
        public static string ToolTip_DefaultText {
            get {
                return ResourceManager.GetString("ToolTip_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Display Name....
        /// </summary>
        public static string Tooltip_DisplayName {
            get {
                return ResourceManager.GetString("Tooltip_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email ID.
        /// </summary>
        public static string ToolTip_EnterEmailID {
            get {
                return ResourceManager.GetString("ToolTip_EnterEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile Number.
        /// </summary>
        public static string ToolTip_EnterMobileNumber {
            get {
                return ResourceManager.GetString("ToolTip_EnterMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Login Name....
        /// </summary>
        public static string Tooltip_LoginName {
            get {
                return ResourceManager.GetString("Tooltip_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ToolTip_LoginPassword {
            get {
                return ResourceManager.GetString("ToolTip_LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string ToolTip_LoginUserName {
            get {
                return ResourceManager.GetString("ToolTip_LoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Tooltip_NewPassword {
            get {
                return ResourceManager.GetString("Tooltip_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string Tooltip_OldPassword {
            get {
                return ResourceManager.GetString("Tooltip_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Order by.
        /// </summary>
        public static string ToolTip_OrderBy {
            get {
                return ResourceManager.GetString("ToolTip_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Role Name.
        /// </summary>
        public static string Tooltip_RoleName {
            get {
                return ResourceManager.GetString("Tooltip_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhar Number.
        /// </summary>
        public static string UserMaster_AadharNumber {
            get {
                return ResourceManager.GetString("UserMaster_AadharNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        public static string UserMaster_Address1 {
            get {
                return ResourceManager.GetString("UserMaster_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        public static string UserMaster_Address2 {
            get {
                return ResourceManager.GetString("UserMaster_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address3.
        /// </summary>
        public static string UserMaster_Address3 {
            get {
                return ResourceManager.GetString("UserMaster_Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salary.
        /// </summary>
        public static string UserMaster_BasicSalary {
            get {
                return ResourceManager.GetString("UserMaster_BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Joining.
        /// </summary>
        public static string UserMaster_DateOfJoining {
            get {
                return ResourceManager.GetString("UserMaster_DateOfJoining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string UserMaster_DisplayName {
            get {
                return ResourceManager.GetString("UserMaster_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserMaster_Email {
            get {
                return ResourceManager.GetString("UserMaster_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Code.
        /// </summary>
        public static string UserMaster_EmployeeCode {
            get {
                return ResourceManager.GetString("UserMaster_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string UserMaster_FirstName {
            get {
                return ResourceManager.GetString("UserMaster_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Allowances.
        /// </summary>
        public static string UserMaster_FoodAllowances {
            get {
                return ResourceManager.GetString("UserMaster_FoodAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string UserMaster_LastName {
            get {
                return ResourceManager.GetString("UserMaster_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        public static string UserMaster_LoginName {
            get {
                return ResourceManager.GetString("UserMaster_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string UserMaster_MobileNumber {
            get {
                return ResourceManager.GetString("UserMaster_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Amount.
        /// </summary>
        public static string UserMaster_OTAmount {
            get {
                return ResourceManager.GetString("UserMaster_OTAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Number.
        /// </summary>
        public static string UserMaster_PanNumber {
            get {
                return ResourceManager.GetString("UserMaster_PanNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserMaster_Password {
            get {
                return ResourceManager.GetString("UserMaster_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string UserMaster_RoleName {
            get {
                return ResourceManager.GetString("UserMaster_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Allowances.
        /// </summary>
        public static string UserMaster_TravelAllowances {
            get {
                return ResourceManager.GetString("UserMaster_TravelAllowances", resourceCulture);
            }
        }
    }
}
