//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePro.Repository.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SYSTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SYSTitle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparePro.Repository.Resource.SYSTitle", typeof(SYSTitle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Message.
        /// </summary>
        public static string RoleMatrix_ConfirmationMessage {
            get {
                return ResourceManager.GetString("RoleMatrix_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Title_ChangePassword {
            get {
                return ResourceManager.GetString("Title_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Message!.
        /// </summary>
        public static string Title_Confirmation_Message {
            get {
                return ResourceManager.GetString("Title_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string Title_DashBoard {
            get {
                return ResourceManager.GetString("Title_DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Title_Login {
            get {
                return ResourceManager.GetString("Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Setup - Search.
        /// </summary>
        public static string Title_Master_Setup_Search {
            get {
                return ResourceManager.GetString("Title_Master_Setup_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Setup - View.
        /// </summary>
        public static string Title_Master_Setup_View {
            get {
                return ResourceManager.GetString("Title_Master_Setup_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Setup.
        /// </summary>
        public static string Title_Project_Setup {
            get {
                return ResourceManager.GetString("Title_Project_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Master - Search.
        /// </summary>
        public static string Title_Role_Master_Search {
            get {
                return ResourceManager.GetString("Title_Role_Master_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Master - View.
        /// </summary>
        public static string Title_Role_Master_View {
            get {
                return ResourceManager.GetString("Title_Role_Master_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Setup - Search.
        /// </summary>
        public static string Title_Role_Setup_Search {
            get {
                return ResourceManager.GetString("Title_Role_Setup_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Setup - View.
        /// </summary>
        public static string Title_Role_Setup_View {
            get {
                return ResourceManager.GetString("Title_Role_Setup_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Master - [Add/Edit].
        /// </summary>
        public static string Title_RoleMaster {
            get {
                return ResourceManager.GetString("Title_RoleMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Matrix Edit Access.
        /// </summary>
        public static string Title_RoleMatrix_EditAccess {
            get {
                return ResourceManager.GetString("Title_RoleMatrix_EditAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In to your account.
        /// </summary>
        public static string Title_SignIn {
            get {
                return ResourceManager.GetString("Title_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Message!.
        /// </summary>
        public static string Title_Success_Message {
            get {
                return ResourceManager.GetString("Title_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Master - Search.
        /// </summary>
        public static string Title_User_Master_Search {
            get {
                return ResourceManager.GetString("Title_User_Master_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Master - View.
        /// </summary>
        public static string Title_User_Master_View {
            get {
                return ResourceManager.GetString("Title_User_Master_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string Title_UserInformation {
            get {
                return ResourceManager.GetString("Title_UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Master - [Add/Edit].
        /// </summary>
        public static string Title_UserMaster_AddEdit {
            get {
                return ResourceManager.GetString("Title_UserMaster_AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Message!.
        /// </summary>
        public static string Title_Warning_Message {
            get {
                return ResourceManager.GetString("Title_Warning_Message", resourceCulture);
            }
        }
    }
}
